export const actionTypes = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOADING: 'LOADING',
  LOADINGCANCEL: 'LOADINGCANCEL',
  MAINLOADING: 'MAINLOADING',
  SETADMINPERMISSION: 'SETADMINPERMISSION',
};
